//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch distinct=&apos;true&apos; version=&apos;1.0&apos;&gt;
        ///	&lt;entity name=&apos;sdkmessage&apos;&gt;
        ///		&lt;attribute name=&apos;name&apos;/&gt;
        ///		&lt;attribute name=&apos;isprivate&apos;/&gt;
        ///		&lt;attribute name=&apos;sdkmessageid&apos;/&gt;
        ///		&lt;attribute name=&apos;customizationlevel&apos;/&gt;
        ///		&lt;link-entity name=&apos;sdkmessagepair&apos; alias=&apos;sdkmessagepair&apos; to=&apos;sdkmessageid&apos; from=&apos;sdkmessageid&apos; link-type=&apos;inner&apos;&gt;
        ///			&lt;filter&gt;
        ///				&lt;condition alias=&apos;sdkmessagepair&apos; attribute=&apos;endpoint&apos; operator=&apos;eq&apos; value=&apos;2011/Organization.svc&apos; /&gt;
        ///			&lt;/filter&gt;
        ///			&lt;attribute name=&apos;sdkmessagepairid&apos;/&gt;
        ///			&lt;attribut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetrieveAllSDKMessages {
            get {
                return ResourceManager.GetString("RetrieveAllSDKMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch distinct=&apos;true&apos; version=&apos;1.0&apos;&gt;
        ///    &lt;entity name=&apos;sdkmessage&apos;&gt;
        ///        &lt;attribute name=&apos;name&apos;/&gt;
        ///        &lt;attribute name=&apos;isprivate&apos;/&gt;
        ///        &lt;attribute name=&apos;sdkmessageid&apos;/&gt;
        ///        &lt;attribute name=&apos;customizationlevel&apos;/&gt;
        ///        &lt;link-entity name=&apos;sdkmessagepair&apos; alias=&apos;sdkmessagepair&apos; to=&apos;sdkmessageid&apos; from=&apos;sdkmessageid&apos; link-type=&apos;inner&apos;&gt;
        ///            &lt;filter&gt;
        ///                &lt;condition alias=&apos;sdkmessagepair&apos; attribute=&apos;endpoint&apos; operator=&apos;eq&apos; value=&apos;2011/Organization.svc&apos; /&gt;
        ///            &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetrieveBaseListOfSdkMessages {
            get {
                return ResourceManager.GetString("RetrieveBaseListOfSdkMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch distinct=&apos;true&apos; version=&apos;1.0&apos; returntotalrecordcount=&apos;true&apos; &gt;
        ///    &lt;entity name=&apos;sdkmessage&apos; &gt;
        ///        &lt;attribute name=&apos;name&apos; /&gt;
        ///        &lt;attribute name=&apos;isprivate&apos; /&gt;
        ///        &lt;attribute name=&apos;sdkmessageid&apos; /&gt;
        ///        &lt;attribute name=&apos;customizationlevel&apos; /&gt;
        ///        &lt;link-entity name=&apos;sdkmessagepair&apos; alias=&apos;sdkmessagepair&apos; to=&apos;sdkmessageid&apos; from=&apos;sdkmessageid&apos; link-type=&apos;inner&apos; &gt;
        ///            &lt;filter&gt;
        ///                &lt;condition alias=&apos;sdkmessagepair&apos; attribute=&apos;endpoint&apos; operator=&apos;eq&apos; value=&apos;201 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetrieveFilterdListOfSdkMessages {
            get {
                return ResourceManager.GetString("RetrieveFilterdListOfSdkMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch distinct=&apos;true&apos; version=&apos;1.0&apos; returntotalrecordcount=&apos;true&apos; &gt;
        ///    &lt;entity name=&apos;sdkmessage&apos; &gt;
        ///        &lt;attribute name=&apos;name&apos; /&gt;
        ///        &lt;attribute name=&apos;isprivate&apos; /&gt;
        ///        &lt;attribute name=&apos;sdkmessageid&apos; /&gt;
        ///        &lt;attribute name=&apos;customizationlevel&apos; /&gt;
        ///        &lt;link-entity name=&apos;sdkmessagepair&apos; alias=&apos;sdkmessagepair&apos; to=&apos;sdkmessageid&apos; from=&apos;sdkmessageid&apos; link-type=&apos;inner&apos; &gt;
        ///            &lt;filter&gt;
        ///                &lt;condition alias=&apos;sdkmessagepair&apos; attribute=&apos;endpoint&apos; operator=&apos;eq&apos; value=&apos;201 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetrieveFilterdSdkMessageListBase {
            get {
                return ResourceManager.GetString("RetrieveFilterdSdkMessageListBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch distinct=&quot;true&quot; version=&quot;1.0&quot; &gt;
        ///    &lt;entity name=&quot;sdkmessage&quot; &gt;
        ///        &lt;attribute name=&quot;sdkmessageid&quot; /&gt;
        ///        &lt;link-entity name=&quot;sdkmessagepair&quot; alias=&quot;sdkmessagepair&quot; to=&quot;sdkmessageid&quot; from=&quot;sdkmessageid&quot; link-type=&quot;inner&quot; &gt;
        ///            &lt;filter&gt;
        ///                &lt;condition alias=&quot;sdkmessagepair&quot; attribute=&quot;endpoint&quot; operator=&quot;eq&quot; value=&quot;2011/Organization.svc&quot; /&gt;
        ///            &lt;/filter&gt;
        ///        &lt;/link-entity&gt;
        ///        &lt;link-entity name=&quot;sdkmessagefilter&quot; alias=&quot;sdmessagefilter&quot; to=&quot;sdkmessage [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetrieveFilteredSdkMessageListToEntity {
            get {
                return ResourceManager.GetString("RetrieveFilteredSdkMessageListToEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch distinct=&quot;true&quot; version=&quot;1.0&quot; &gt;
        ///    &lt;entity name=&quot;sdkmessage&quot; &gt;
        ///        &lt;attribute name=&quot;sdkmessageid&quot; /&gt;
        ///        &lt;link-entity name=&quot;sdkmessagepair&quot; alias=&quot;sdkmessagepair&quot; to=&quot;sdkmessageid&quot; from=&quot;sdkmessageid&quot; link-type=&quot;inner&quot; &gt;
        ///            &lt;filter&gt;
        ///                &lt;condition alias=&quot;sdkmessagepair&quot; attribute=&quot;endpoint&quot; operator=&quot;eq&quot; value=&quot;2011/Organization.svc&quot; /&gt;
        ///            &lt;/filter&gt;
        ///        &lt;/link-entity&gt;
        ///        &lt;link-entity name=&quot;sdkmessagefilter&quot; alias=&quot;sdmessagefilter&quot; to=&quot;sdkmessage [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetrieveSdkMessageToEntity {
            get {
                return ResourceManager.GetString("RetrieveSdkMessageToEntity", resourceCulture);
            }
        }
    }
}
